//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Cars.Datenbank
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResStatus
    {
        public ResStatus()
        {
            this.Reservierung = new HashSet<Reservierung>();
        }
    
        public int ResStatus_ID { get; set; }
        public string Statusbezeichnung { get; set; }
    
        public virtual ICollection<Reservierung> Reservierung { get; set; }
    }
}
